// +build !ignore_autogenerated

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/knabben/chatops/pkg/apis/chat/v1alpha1.Chat":       schema_pkg_apis_chat_v1alpha1_Chat(ref),
		"github.com/knabben/chatops/pkg/apis/chat/v1alpha1.ChatSpec":   schema_pkg_apis_chat_v1alpha1_ChatSpec(ref),
		"github.com/knabben/chatops/pkg/apis/chat/v1alpha1.ChatStatus": schema_pkg_apis_chat_v1alpha1_ChatStatus(ref),
	}
}

func schema_pkg_apis_chat_v1alpha1_Chat(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Chat is the Schema for the chats API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/knabben/chatops/pkg/apis/chat/v1alpha1.ChatSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/knabben/chatops/pkg/apis/chat/v1alpha1.ChatStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/knabben/chatops/pkg/apis/chat/v1alpha1.ChatSpec", "github.com/knabben/chatops/pkg/apis/chat/v1alpha1.ChatStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_chat_v1alpha1_ChatSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ChatSpec defines the desired state of Chat",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_chat_v1alpha1_ChatStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "ChatStatus defines the observed state of Chat",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
